"""
VICTIG Document Fraud Detector v2.0
Enhanced with AI Vision Analysis
"""

import streamlit as st
import os
import io
from datetime import datetime
from document_analyzer import DocumentAnalyzer
from fpdf import FPDF

st.set_page_config(
    page_title="VICTIG Document Fraud Detector",
    page_icon="🔍",
    layout="wide"
)

# Custom CSS
st.markdown("""
<style>
    .risk-high { 
        color: #dc3545; 
        font-size: 2.5rem;
        font-weight: bold; 
    }
    .risk-medium { 
        color: #ffc107; 
        font-size: 2.5rem;
        font-weight: bold; 
    }
    .risk-low { 
        color: #28a745; 
        font-size: 2.5rem;
        font-weight: bold; 
    }
    .flag-item { 
        padding: 12px; 
        margin: 8px 0; 
        border-radius: 6px; 
    }
    .flag-critical { 
        background-color: #f8d7da; 
        border-left: 5px solid #dc3545; 
    }
    .flag-warning { 
        background-color: #fff3cd; 
        border-left: 5px solid #ffc107; 
    }
    .flag-info { 
        background-color: #d1ecf1; 
        border-left: 5px solid #17a2b8; 
    }
    .recommendation-box {
        background-color: #f8f9fa;
        border-radius: 8px;
        padding: 15px;
        margin: 10px 0;
    }
    .ai-box {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 10px;
        padding: 20px;
        margin: 15px 0;
    }
    .ai-assessment {
        font-size: 1.5rem;
        font-weight: bold;
        margin-bottom: 10px;
    }
    .score-gauge {
        height: 20px;
        background-color: #e9ecef;
        border-radius: 10px;
        overflow: hidden;
        margin: 10px 0;
    }
    .score-fill {
        height: 100%;
        transition: width 0.5s ease-in-out;
    }
    .metadata-grid {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        gap: 10px;
    }
</style>
""", unsafe_allow_html=True)

# Header
col1, col2 = st.columns([3, 1])
with col1:
    st.title("🔍 VICTIG Document Fraud Detector")
    st.markdown("*AI-powered analysis for employment verification documents*")
with col2:
    st.markdown("### v2.0")
    ai_status = "🟢 AI Enabled" if os.environ.get('ANTHROPIC_API_KEY') else "⚪ AI Disabled"
    st.caption(ai_status)

# Sidebar
with st.sidebar:
    # Navigation
    page = st.radio("Navigation", ["🔍 Analyze Document", "📖 About & Methodology"], label_visibility="collapsed")
    
    st.divider()
    
    st.header("📋 Document Types")
    st.markdown("""
    **Supported:**
    - ✅ Pay Stubs
    - ✅ W-2 Forms
    - ✅ 1099 Forms
    - ✅ Offer Letters
    - ✅ Diplomas/Transcripts
    
    **Formats:** PDF, PNG, JPG
    """)
    
    st.divider()
    
    st.header("🎯 Risk Levels")
    st.markdown("""
    🔴 **HIGH** (50+) - Strong fraud indicators  
    🟡 **MEDIUM** (25-49) - Suspicious, needs review  
    🟢 **LOW** (0-24) - Appears legitimate
    """)
    
    st.divider()
    
    # Settings
    st.header("⚙️ Settings")
    use_ai = st.checkbox("Enable AI Analysis", value=True, 
                         disabled=not os.environ.get('ANTHROPIC_API_KEY'),
                         help="Uses Claude AI for deep document analysis")

# About & Methodology Page
if page == "📖 About & Methodology":
    st.header("📖 Document Verification Methodology")
    st.markdown("""
    VICTIG's Document Fraud Detector uses a multi-layered approach to identify potentially 
    fraudulent employment verification documents. Our system combines traditional forensic 
    techniques with advanced AI analysis to provide comprehensive fraud detection.
    """)
    
    st.subheader("🔬 Analysis Methods")
    
    with st.expander("1. Metadata Forensics", expanded=True):
        st.markdown("""
        **What we check:**
        - **Creation Date & Time** — When was the document actually created? A "January 2024" pay stub created yesterday is suspicious.
        - **Modification History** — Has the document been edited after creation?
        - **Creator Software** — Was this generated by legitimate payroll software (ADP, Paychex, Gusto, Workday, etc.) or by image/document editors (Photoshop, Canva, Word)?
        - **File Integrity** — Does the file structure match what it claims to be?
        
        **Why it matters:**
        Legitimate payroll documents come directly from payroll systems with consistent metadata. 
        Documents created in image editors or recently fabricated leave telltale digital fingerprints.
        
        **Legitimate Sources We Recognize:**
        ADP, Paychex, Gusto, Workday, UltiPro/UKG, Ceridian Dayforce, Paylocity, Paycom, 
        BambooHR, Namely, Zenefits, QuickBooks, Sage, Oracle HCM, SAP SuccessFactors, 
        Kronos, Square Payroll, Rippling, and more.
        """)
    
    with st.expander("2. Mathematical Validation", expanded=True):
        st.markdown("""
        **Pay Stub Checks:**
        - Net pay cannot exceed gross pay
        - Hours × Hourly Rate should equal gross pay (within tolerance)
        - Deduction percentages should fall within reasonable ranges (typically 15-45%)
        - Federal withholding rates should match income brackets
        
        **W-2 Checks:**
        - Social Security tax = 6.2% of wages (up to annual cap)
        - Medicare tax = 1.45% of wages
        - Box 1, 3, and 5 wages should be consistent (with known exceptions)
        - Federal withholding cannot exceed 37% of wages
        
        **Why it matters:**
        Fraudsters often change numbers without understanding tax law. A pay stub showing 
        $5,000 gross and $4,800 net (only 4% deductions) is mathematically impossible 
        for any legitimate US employee.
        """)
    
    with st.expander("3. Text & Content Analysis", expanded=True):
        st.markdown("""
        **What we scan for:**
        - **Placeholder text** — "Lorem ipsum", "John Doe", "[Company Name]", "SAMPLE"
        - **Inconsistent date formats** — Mixing MM/DD/YYYY with YYYY-MM-DD suggests copy-paste from multiple sources
        - **Suspicious phrases** — "proof of income", "generated for verification" (real pay stubs don't say this)
        - **Template indicators** — Signs the document came from a fill-in-the-blank template
        
        **Why it matters:**
        Legitimate payroll systems produce consistent, professional output. Fabricated documents 
        often contain subtle inconsistencies or remnants of the templates used to create them.
        """)
    
    with st.expander("4. Visual Forensics", expanded=True):
        st.markdown("""
        **Image Analysis:**
        - **Resolution quality** — Is this a proper scan or a screenshot of a screenshot?
        - **Aspect ratio** — Does it match standard paper sizes (Letter, A4)?
        - **Color profile** — Pay stubs are typically on white paper; unusual coloring is flagged
        - **Edge artifacts** — Cut-and-paste operations leave detectable edges
        - **Noise patterns** — Edited regions often have different noise characteristics than originals
        
        **Why it matters:**
        Even sophisticated edits leave traces. Our forensic analysis detects inconsistencies 
        invisible to the naked eye.
        """)
    
    with st.expander("5. AI Vision Analysis", expanded=True):
        st.markdown("""
        **Powered by Claude AI:**
        - **Visual consistency** — Are fonts, spacing, and alignment uniform throughout?
        - **Template authenticity** — Does this look like output from a real payroll system?
        - **Manipulation detection** — Identifying signs of digital editing, cloning, or compositing
        - **Holistic assessment** — Combining all visual elements for an overall fraud likelihood
        
        **What AI catches that rules miss:**
        - Text that "floats" unnaturally on the page
        - Logos that appear copied or low-resolution
        - Subtle font mismatches between sections
        - Areas that appear sharpened or blurred differently than surrounding content
        - "Too perfect" templated appearances
        
        **Why it matters:**
        AI can detect patterns across thousands of legitimate documents and identify when 
        something "just doesn't look right" — even when individual elements pass basic checks.
        """)
    
    st.divider()
    
    st.subheader("📊 Risk Scoring")
    st.markdown("""
    Each flag detected adds to the cumulative risk score:
    
    | Severity | Score Impact | Examples |
    |----------|--------------|----------|
    | 🔴 Critical | +30 to +50 | AI generation detected, net > gross, Photoshop creator |
    | 🟡 Warning | +10 to +25 | Recent creation date, unusual software, tax rate anomalies |
    | 🔵 Info | +5 to +10 | Low resolution, unusual dimensions |
    | ✅ Positive | -10 to -15 | Legitimate payroll software detected, AI confirms authenticity |
    
    **Final Risk Levels:**
    - 🔴 **HIGH (50+):** Strong fraud indicators — request alternative documentation
    - 🟡 **MEDIUM (25-49):** Suspicious elements — additional verification recommended  
    - 🟢 **LOW (0-24):** Appears legitimate — standard review sufficient
    """)
    
    st.divider()
    
    st.subheader("🔒 Privacy & Security")
    st.markdown("""
    - Documents are processed locally and not stored after analysis
    - AI analysis uses encrypted connections
    - No document content is retained or used for training
    - File hashes are generated for audit trails only
    """)
    
    st.divider()
    st.caption("VICTIG Document Fraud Detector v2.0 | For internal use only")
    st.stop()

# Main content - Analyze Document page
uploaded_file = st.file_uploader(
    "📤 Upload Document for Analysis",
    type=['pdf', 'png', 'jpg', 'jpeg'],
    help="Upload a pay stub, W-2, or other employment document"
)

col1, col2 = st.columns(2)
with col1:
    doc_type = st.selectbox(
        "Document Type",
        ["Pay Stub", "W-2", "1099", "Offer Letter", "Diploma/Transcript", "Other"],
        help="Select the type of document for specialized analysis"
    )
with col2:
    candidate_ref = st.text_input(
        "Candidate Reference (Optional)",
        placeholder="e.g., Applicant ID or Name",
        help="For tracking purposes"
    )

if uploaded_file:
    st.divider()
    
    # Save uploaded file temporarily
    temp_path = f"/tmp/{uploaded_file.name}"
    with open(temp_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
    
    # Progress indicator
    progress_bar = st.progress(0)
    status_text = st.empty()
    
    status_text.text("🔍 Extracting metadata...")
    progress_bar.progress(20)
    
    # Run analysis
    analyzer = DocumentAnalyzer(use_ai=use_ai and bool(os.environ.get('ANTHROPIC_API_KEY')))
    
    status_text.text("📊 Analyzing document structure...")
    progress_bar.progress(40)
    
    status_text.text("🧮 Validating data...")
    progress_bar.progress(60)
    
    if use_ai and os.environ.get('ANTHROPIC_API_KEY'):
        status_text.text("🤖 Running AI vision analysis...")
    progress_bar.progress(80)
    
    results = analyzer.analyze(temp_path, doc_type)
    
    progress_bar.progress(100)
    status_text.text("✅ Analysis complete!")
    
    # Clear progress after a moment
    import time
    time.sleep(0.5)
    progress_bar.empty()
    status_text.empty()
    
    # Results display
    col1, col2 = st.columns([1, 2])
    
    with col1:
        st.subheader("📊 Risk Assessment")
        
        risk_score = results.get('risk_score', 0)
        risk_level = results.get('risk_level', 'Unknown')
        
        # Risk level display
        if risk_level == 'HIGH':
            st.markdown(f"<div class='risk-high'>🔴 HIGH RISK</div>", unsafe_allow_html=True)
            bar_color = "#dc3545"
        elif risk_level == 'MEDIUM':
            st.markdown(f"<div class='risk-medium'>🟡 MEDIUM RISK</div>", unsafe_allow_html=True)
            bar_color = "#ffc107"
        else:
            st.markdown(f"<div class='risk-low'>🟢 LOW RISK</div>", unsafe_allow_html=True)
            bar_color = "#28a745"
        
        # Score gauge
        st.markdown(f"""
        <div class="score-gauge">
            <div class="score-fill" style="width: {min(risk_score, 100)}%; background-color: {bar_color};"></div>
        </div>
        <center><strong>Score: {risk_score}/100</strong></center>
        """, unsafe_allow_html=True)
        
        st.markdown("---")
        
        # Document preview
        st.subheader("📄 Document")
        if uploaded_file.type == "application/pdf":
            st.info("PDF Document")
            # Could add PDF preview here with pdf2image
        else:
            st.image(uploaded_file, use_container_width=True)
        
        # File info
        st.caption(f"**File:** {uploaded_file.name}")
        st.caption(f"**Hash:** {results.get('file_hash', 'N/A')}")
        st.caption(f"**Analyzed:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    
    with col2:
        # Tabs for different result sections
        tab1, tab2, tab3, tab4 = st.tabs(["🚩 Flags", "🤖 AI Analysis", "📋 Details", "💡 Actions"])
        
        with tab1:
            st.subheader("Fraud Indicators")
            
            flags = results.get('flags', [])
            critical = [f for f in flags if f.get('severity') == 'critical']
            warnings = [f for f in flags if f.get('severity') == 'warning']
            info = [f for f in flags if f.get('severity') == 'info']
            
            if not flags:
                st.success("✅ No significant fraud indicators detected.")
            else:
                if critical:
                    st.markdown("#### 🔴 Critical Issues")
                    for flag in critical:
                        st.markdown(f"""
                        <div class='flag-item flag-critical'>
                            <strong>{flag['title']}</strong><br>
                            {flag['description']}
                        </div>
                        """, unsafe_allow_html=True)
                
                if warnings:
                    st.markdown("#### 🟡 Warnings")
                    for flag in warnings:
                        st.markdown(f"""
                        <div class='flag-item flag-warning'>
                            <strong>{flag['title']}</strong><br>
                            {flag['description']}
                        </div>
                        """, unsafe_allow_html=True)
                
                if info:
                    st.markdown("#### 🔵 Information")
                    for flag in info:
                        st.markdown(f"""
                        <div class='flag-item flag-info'>
                            <strong>{flag['title']}</strong><br>
                            {flag['description']}
                        </div>
                        """, unsafe_allow_html=True)
        
        with tab2:
            st.subheader("AI Vision Analysis")
            
            ai_analysis = results.get('ai_analysis', {})
            
            if not ai_analysis.get('available', False):
                if not os.environ.get('ANTHROPIC_API_KEY'):
                    st.warning("⚠️ AI analysis requires ANTHROPIC_API_KEY to be set.")
                    st.code("export ANTHROPIC_API_KEY=your_key_here")
                else:
                    st.info(f"AI analysis unavailable: {ai_analysis.get('reason', ai_analysis.get('error', 'Unknown'))}")
            else:
                ai_result = ai_analysis.get('result', {})
                
                if 'overall_assessment' in ai_result:
                    assessment = ai_result['overall_assessment']
                    confidence = ai_result.get('confidence', 0)
                    
                    # Assessment badge
                    if assessment == 'LIKELY_FRAUDULENT':
                        badge_color = "#dc3545"
                        badge_text = "🚨 LIKELY FRAUDULENT"
                    elif assessment == 'SUSPICIOUS':
                        badge_color = "#ffc107"
                        badge_text = "⚠️ SUSPICIOUS"
                    else:
                        badge_color = "#28a745"
                        badge_text = "✅ LIKELY LEGITIMATE"
                    
                    st.markdown(f"""
                    <div class="ai-box">
                        <div class="ai-assessment">{badge_text}</div>
                        <div>AI Confidence: {confidence}%</div>
                    </div>
                    """, unsafe_allow_html=True)
                    
                    # Key findings
                    if ai_result.get('key_findings'):
                        st.markdown("#### 🔑 Key Findings")
                        for finding in ai_result['key_findings']:
                            st.markdown(f"• {finding}")
                    
                    # Visual consistency
                    if ai_result.get('visual_consistency'):
                        vc = ai_result['visual_consistency']
                        with st.expander(f"Visual Consistency (Score: {vc.get('score', 'N/A')}/100)"):
                            if vc.get('issues'):
                                for issue in vc['issues']:
                                    st.markdown(f"- {issue}")
                            else:
                                st.markdown("No visual consistency issues detected.")
                    
                    # Template authenticity
                    if ai_result.get('template_authenticity'):
                        ta = ai_result['template_authenticity']
                        with st.expander(f"Template Analysis (Score: {ta.get('score', 'N/A')}/100)"):
                            if ta.get('appears_to_be'):
                                st.markdown(f"**Source:** {ta['appears_to_be']}")
                            if ta.get('concerns'):
                                st.markdown("**Concerns:**")
                                for concern in ta['concerns']:
                                    st.markdown(f"- {concern}")
                    
                    # Manipulation indicators
                    if ai_result.get('manipulation_indicators', {}).get('detected'):
                        mi = ai_result['manipulation_indicators']
                        with st.expander("🔴 Manipulation Indicators Detected", expanded=True):
                            for indicator in mi.get('indicators', []):
                                st.error(indicator)
                    
                    # AI recommendation
                    if ai_result.get('recommendation'):
                        st.info(f"**AI Recommendation:** {ai_result['recommendation']}")
                
                else:
                    # Raw response fallback
                    st.markdown("#### AI Analysis Response")
                    if 'raw_analysis' in ai_result:
                        st.markdown(ai_result['raw_analysis'])
                    else:
                        st.json(ai_result)
        
        with tab3:
            col_a, col_b = st.columns(2)
            
            with col_a:
                st.markdown("#### 📋 Metadata")
                metadata = results.get('metadata', {})
                st.markdown(f"**File Type:** {metadata.get('file_type', 'Unknown')}")
                st.markdown(f"**Size:** {metadata.get('file_size', 'Unknown')}")
                st.markdown(f"**Created:** {metadata.get('creation_date', 'Unknown')}")
                st.markdown(f"**Modified:** {metadata.get('modification_date', 'N/A')}")
                st.markdown(f"**Creator:** {metadata.get('creator', 'Unknown') or 'Not specified'}")
                st.markdown(f"**Producer:** {metadata.get('producer', 'N/A') or 'N/A'}")
                
                if metadata.get('pages'):
                    st.markdown(f"**Pages:** {metadata.get('pages')}")
            
            with col_b:
                st.markdown("#### 📝 Extracted Data")
                extracted = results.get('extracted_data', {})
                if extracted:
                    for key, value in extracted.items():
                        display_key = key.replace('_', ' ').title()
                        if isinstance(value, float):
                            st.markdown(f"**{display_key}:** ${value:,.2f}")
                        else:
                            st.markdown(f"**{display_key}:** {value}")
                else:
                    st.info("No structured data extracted")
            
            # Math validation
            math = results.get('math_validation')
            if math and (math.get('checks') or math.get('errors')):
                st.markdown("#### 🧮 Math Validation")
                if math.get('errors'):
                    for error in math['errors']:
                        st.error(f"**{error.get('check')}:** {error.get('error')}")
                if math.get('checks'):
                    for check in math['checks']:
                        st.success(f"✓ {check}")
            
            # Visual forensics
            visual = results.get('visual_analysis', {})
            if visual.get('checks_performed'):
                with st.expander("🔬 Visual Forensics"):
                    st.markdown(f"**Resolution:** {visual.get('resolution', 'N/A')}")
                    st.markdown(f"**Aspect Ratio:** {visual.get('aspect_ratio', 'N/A')}")
                    st.markdown(f"**Brightness:** {visual.get('mean_brightness', 'N/A')}")
                    st.markdown(f"**Checks:** {', '.join(visual.get('checks_performed', []))}")
        
        with tab4:
            st.subheader("💡 Recommendations")
            
            recommendations = results.get('recommendations', [])
            st.markdown('<div class="recommendation-box">', unsafe_allow_html=True)
            for rec in recommendations:
                st.markdown(f"**{rec}**")
            st.markdown('</div>', unsafe_allow_html=True)
            
            st.markdown("---")
            
            st.subheader("📋 Actions")
            
            col_btn1, col_btn2, col_btn3 = st.columns(3)
            
            with col_btn1:
                if st.button("📧 Flag for Review", use_container_width=True):
                    st.toast("✅ Document flagged for supervisor review")
            
            with col_btn2:
                if st.button("✓ Mark as Verified", use_container_width=True):
                    st.toast("✅ Document marked as verified")
            
            with col_btn3:
                if st.button("🚫 Mark as Rejected", use_container_width=True, type="primary" if risk_level == 'HIGH' else "secondary"):
                    st.toast("Document marked as rejected")
            
            # Export reports
            st.markdown("---")
            st.markdown("#### 📄 Generate Reports")
            
            col_r1, col_r2 = st.columns(2)
            
            with col_r1:
                # Internal detailed report
                if st.button("📋 Internal Report", use_container_width=True, help="Detailed report for VICTIG team"):
                    report = f"""
VICTIG DOCUMENT FRAUD ANALYSIS REPORT (INTERNAL)
=================================================
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Analyst: VICTIG Verification Team
Candidate: {candidate_ref or 'Not specified'}
Document: {uploaded_file.name}
Document Hash: {results.get('file_hash', 'N/A')}
Type: {doc_type}

RISK ASSESSMENT
---------------
Risk Level: {risk_level}
Risk Score: {risk_score}/100

FLAGS DETECTED ({len(flags)})
--------------
"""
                    for flag in flags:
                        severity = flag.get('severity', '').upper()
                        report += f"[{severity}] {flag['title']}\n"
                        report += f"  {flag['description']}\n\n"
                    
                    report += """
RECOMMENDATIONS
---------------
"""
                    for rec in recommendations:
                        report += f"• {rec}\n"
                    
                    st.download_button(
                        "⬇️ Download Internal Report",
                        report,
                        file_name=f"fraud_report_internal_{datetime.now().strftime('%Y%m%d_%H%M')}.txt",
                        mime="text/plain"
                    )
            
            with col_r2:
                # Customer-facing report (PDF)
                if st.button("📨 Customer Report (PDF)", use_container_width=True, type="primary", help="Professional PDF report to share with customers"):
                    # Determine result summary
                    if risk_level == 'HIGH':
                        result_text = "ADDITIONAL VERIFICATION REQUIRED"
                        result_detail = "Our analysis identified elements in this document that require additional verification before we can proceed."
                        result_color = (220, 53, 69)  # Red
                    elif risk_level == 'MEDIUM':
                        result_text = "VERIFICATION IN PROGRESS"
                        result_detail = "Our analysis identified elements that warrant additional review. We may request supplementary documentation."
                        result_color = (255, 193, 7)  # Yellow
                    else:
                        result_text = "DOCUMENT VERIFIED"
                        result_detail = "This document has passed our verification checks and appears to be authentic."
                        result_color = (40, 167, 69)  # Green
                    
                    # Build checks performed list
                    checks_performed = [
                        "Document metadata analysis",
                        "Creation date and source verification", 
                        "Mathematical consistency validation",
                        "Format and structure analysis",
                    ]
                    if use_ai and os.environ.get('ANTHROPIC_API_KEY'):
                        checks_performed.append("AI-powered visual authenticity analysis")
                    
                    # Create PDF
                    pdf = FPDF()
                    pdf.add_page()
                    pdf.set_auto_page_break(auto=True, margin=15)
                    
                    # Header
                    pdf.set_fill_color(0, 51, 102)  # Navy blue
                    pdf.rect(0, 0, 210, 40, 'F')
                    pdf.set_text_color(255, 255, 255)
                    pdf.set_font('Helvetica', 'B', 24)
                    pdf.set_y(12)
                    pdf.cell(0, 10, 'VICTIG', align='C', ln=True)
                    pdf.set_font('Helvetica', '', 12)
                    pdf.cell(0, 8, 'Background Screening Services', align='C', ln=True)
                    
                    # Reset text color
                    pdf.set_text_color(0, 0, 0)
                    pdf.set_y(50)
                    
                    # Title
                    pdf.set_font('Helvetica', 'B', 18)
                    pdf.cell(0, 10, 'Document Verification Report', align='C', ln=True)
                    pdf.ln(5)
                    
                    # Document Info Box
                    pdf.set_fill_color(245, 245, 245)
                    pdf.rect(15, pdf.get_y(), 180, 30, 'F')
                    pdf.set_font('Helvetica', '', 10)
                    y_start = pdf.get_y() + 5
                    pdf.set_xy(20, y_start)
                    pdf.cell(85, 6, f"Report Date: {datetime.now().strftime('%B %d, %Y')}", ln=False)
                    pdf.cell(85, 6, f"Document Type: {doc_type}", ln=True)
                    pdf.set_x(20)
                    pdf.cell(85, 6, f"Reference: {candidate_ref or 'N/A'}", ln=False)
                    pdf.cell(85, 6, f"Document ID: {results.get('file_hash', 'N/A')[:8].upper()}", ln=True)
                    pdf.ln(15)
                    
                    # Result Box
                    pdf.set_fill_color(*result_color)
                    pdf.rect(15, pdf.get_y(), 180, 25, 'F')
                    pdf.set_text_color(255, 255, 255)
                    pdf.set_font('Helvetica', 'B', 16)
                    pdf.set_y(pdf.get_y() + 5)
                    pdf.cell(0, 10, result_text, align='C', ln=True)
                    pdf.set_font('Helvetica', '', 10)
                    pdf.set_text_color(0, 0, 0)
                    pdf.ln(15)
                    
                    # Result detail
                    pdf.set_font('Helvetica', '', 11)
                    pdf.multi_cell(0, 6, result_detail)
                    pdf.ln(10)
                    
                    # Verification Process Section
                    pdf.set_font('Helvetica', 'B', 14)
                    pdf.set_fill_color(0, 51, 102)
                    pdf.set_text_color(255, 255, 255)
                    pdf.cell(0, 10, '  VERIFICATION PROCESS', fill=True, ln=True)
                    pdf.set_text_color(0, 0, 0)
                    pdf.ln(5)
                    
                    pdf.set_font('Helvetica', '', 11)
                    pdf.cell(0, 6, 'The following verification checks were performed:', ln=True)
                    pdf.ln(3)
                    
                    for check in checks_performed:
                        pdf.set_font('Helvetica', '', 11)
                        pdf.cell(10, 6, '', ln=False)  # Indent
                        pdf.set_font('ZapfDingbats', '', 10)
                        pdf.cell(8, 6, '4', ln=False)  # Checkmark
                        pdf.set_font('Helvetica', '', 11)
                        pdf.cell(0, 6, f'  {check}', ln=True)
                    pdf.ln(10)
                    
                    # About Our Process Section
                    pdf.set_font('Helvetica', 'B', 14)
                    pdf.set_fill_color(0, 51, 102)
                    pdf.set_text_color(255, 255, 255)
                    pdf.cell(0, 10, '  ABOUT OUR PROCESS', fill=True, ln=True)
                    pdf.set_text_color(0, 0, 0)
                    pdf.ln(5)
                    
                    pdf.set_font('Helvetica', '', 10)
                    about_text = "VICTIG employs industry-leading document verification technology to ensure the authenticity of employment verification documents. Our multi-layered analysis includes:"
                    pdf.multi_cell(0, 5, about_text)
                    pdf.ln(5)
                    
                    methods = [
                        ("Metadata Forensics", "We examine the digital fingerprint of each document, including creation timestamps, source software, and modification history."),
                        ("Mathematical Validation", "Financial figures are cross-checked for mathematical consistency, including tax calculations and pay calculations."),
                        ("Format Analysis", "Documents are compared against known legitimate formats from major payroll providers."),
                        ("AI-Powered Visual Analysis", "Advanced AI examines documents for signs of digital manipulation or visual inconsistencies.")
                    ]
                    
                    for method_name, method_desc in methods:
                        pdf.set_font('Helvetica', 'B', 10)
                        pdf.cell(0, 6, f"  {method_name}", ln=True)
                        pdf.set_font('Helvetica', '', 9)
                        pdf.set_x(20)
                        pdf.multi_cell(170, 5, method_desc)
                        pdf.ln(2)
                    
                    pdf.ln(5)
                    
                    # Next Steps Section
                    pdf.set_font('Helvetica', 'B', 14)
                    pdf.set_fill_color(0, 51, 102)
                    pdf.set_text_color(255, 255, 255)
                    pdf.cell(0, 10, '  NEXT STEPS', fill=True, ln=True)
                    pdf.set_text_color(0, 0, 0)
                    pdf.ln(5)
                    
                    pdf.set_font('Helvetica', '', 11)
                    if risk_level == 'HIGH':
                        next_steps = "We require additional documentation to complete verification. Please provide one of the following:\n\n- Original pay stub directly from your payroll portal (PDF download)\n- Bank statement showing matching deposit amounts\n- Direct employer verification via HR contact\n\nContact your VICTIG representative for assistance."
                    elif risk_level == 'MEDIUM':
                        next_steps = "A member of our verification team may reach out for additional information. No action is required at this time unless contacted."
                    else:
                        next_steps = "No further action is required. This document has been accepted for employment verification purposes."
                    pdf.multi_cell(0, 6, next_steps)
                    
                    # Footer
                    pdf.set_y(-30)
                    pdf.set_font('Helvetica', '', 8)
                    pdf.set_text_color(128, 128, 128)
                    pdf.cell(0, 5, 'This report is confidential and intended for authorized use only.', align='C', ln=True)
                    pdf.cell(0, 5, f'VICTIG Background Screening Services | victig.com | Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', align='C', ln=True)
                    
                    # Output PDF to bytes
                    pdf_bytes = pdf.output()
                    
                    st.download_button(
                        "⬇️ Download PDF Report",
                        data=bytes(pdf_bytes),
                        file_name=f"VICTIG_Verification_Report_{datetime.now().strftime('%Y%m%d')}.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )
    
    # Cleanup
    os.remove(temp_path)

# Footer
st.divider()
col1, col2, col3 = st.columns(3)
with col1:
    st.caption("VICTIG Document Fraud Detector v2.0")
with col2:
    st.caption("🔒 For internal use only")
with col3:
    st.caption(f"Session: {datetime.now().strftime('%Y-%m-%d')}")
