"""
Document Analyzer v2.0
Enhanced fraud detection with AI vision analysis for employment documents.
"""

import os
import re
import base64
import json
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional
from pathlib import Path
import hashlib

# PDF handling
try:
    import fitz  # PyMuPDF
    HAS_PYMUPDF = True
except ImportError:
    HAS_PYMUPDF = False

# Image handling
from PIL import Image, ImageFilter, ImageChops, ImageStat
import io
import numpy as np

# OCR
try:
    import pytesseract
    HAS_TESSERACT = True
except ImportError:
    HAS_TESSERACT = False

# AI Analysis
try:
    import anthropic
    HAS_ANTHROPIC = True
except ImportError:
    HAS_ANTHROPIC = False


class DocumentAnalyzer:
    """Enhanced document fraud detection with AI capabilities."""
    
    # Known legitimate payroll software
    LEGITIMATE_CREATORS = {
        'adp': 'ADP Payroll',
        'paychex': 'Paychex',
        'gusto': 'Gusto',
        'workday': 'Workday',
        'ultipro': 'UltiPro/UKG',
        'ceridian': 'Ceridian Dayforce',
        'paylocity': 'Paylocity',
        'paycom': 'Paycom',
        'bamboohr': 'BambooHR',
        'namely': 'Namely',
        'zenefits': 'Zenefits',
        'quickbooks': 'QuickBooks',
        'sage': 'Sage',
        'oracle': 'Oracle HCM',
        'sap': 'SAP SuccessFactors',
        'kronos': 'Kronos/UKG',
        'adp workforce': 'ADP Workforce Now',
        'intuit': 'Intuit Payroll',
        'square': 'Square Payroll',
        'rippling': 'Rippling',
    }
    
    # Suspicious creation tools - weighted by risk
    # Scores reduced 2026-05-21 to reduce false positives from common legitimate scenarios
    SUSPICIOUS_CREATORS = {
        # High risk - image editors (these are genuinely suspicious)
        'photoshop': ('Adobe Photoshop', 45),
        'gimp': ('GIMP', 40),
        'illustrator': ('Adobe Illustrator', 40),
        'inkscape': ('Inkscape', 35),
        'affinity': ('Affinity', 35),
        'pixelmator': ('Pixelmator', 35),
        'paint.net': ('Paint.NET', 30),
        
        # Medium risk - document editors (reduced - HR legitimately uses these)
        'canva': ('Canva', 30),
        'microsoft word': ('Microsoft Word', 12),  # Reduced from 25 - HR uses Word
        'libreoffice': ('LibreOffice', 15),
        'openoffice': ('OpenOffice', 15),
        'pages': ('Apple Pages', 12),
        'google docs': ('Google Docs', 12),
        
        # PDF editors - medium-high risk
        'acrobat pro': ('Adobe Acrobat Pro', 20),  # Reduced - sometimes used legitimately
        'pdf editor': ('PDF Editor', 35),
        'foxit': ('Foxit PDF', 20),
        'nitro': ('Nitro PDF', 20),
        'smallpdf': ('SmallPDF', 30),
        'ilovepdf': ('iLovePDF', 30),
        'sejda': ('Sejda', 30),
        'pdf-xchange': ('PDF-XChange', 20),
        'pdfelement': ('PDFelement', 25),
        
        # Low/no risk - common legitimate tools
        'preview': ('macOS Preview', 5),  # Reduced from 15 - just scanning
        'microsoft print': ('Microsoft Print to PDF', 0),  # Reduced from 10 - completely normal
    }
    
    # AI-related indicators - highest risk
    AI_INDICATORS = [
        ('chatgpt', 50),
        ('openai', 45),
        ('anthropic', 45),
        ('midjourney', 50),
        ('dall-e', 50),
        ('stable diffusion', 50),
        ('ai generated', 50),
        ('generated by ai', 50),
    ]
    
    # Expected tax withholding ranges by income bracket (2024 US)
    TAX_BRACKETS = [
        (11600, 0.10, 0.15),    # 10% bracket - expect 5-15%
        (47150, 0.12, 0.20),    # 12% bracket - expect 10-20%
        (100525, 0.22, 0.28),   # 22% bracket - expect 18-28%
        (191950, 0.24, 0.32),   # 24% bracket - expect 20-32%
        (243725, 0.32, 0.38),   # 32% bracket - expect 28-38%
        (609350, 0.35, 0.42),   # 35% bracket - expect 32-42%
        (float('inf'), 0.37, 0.45),  # 37% bracket
    ]
    
    def __init__(self, use_ai: bool = True):
        self.flags: List[Dict] = []
        self.risk_score = 0
        self.use_ai = use_ai and HAS_ANTHROPIC and os.environ.get('ANTHROPIC_API_KEY')
        self.ai_client = anthropic.Anthropic() if self.use_ai else None
        
    def analyze(self, file_path: str, doc_type: str = "Pay Stub") -> Dict[str, Any]:
        """Main analysis entry point."""
        self.flags = []
        self.risk_score = 0
        
        results = {
            'file_path': file_path,
            'file_hash': self._compute_hash(file_path),
            'doc_type': doc_type,
            'analyzed_at': datetime.now().isoformat(),
            'metadata': {},
            'flags': [],
            'risk_score': 0,
            'risk_level': 'LOW',
            'extracted_data': {},
            'math_validation': None,
            'visual_analysis': None,
            'ai_analysis': None,
            'recommendations': [],
        }
        
        # Determine file type
        ext = Path(file_path).suffix.lower()
        
        if ext == '.pdf':
            results['metadata'] = self._analyze_pdf_metadata(file_path)
            text = self._extract_pdf_text(file_path)
            image = self._pdf_to_image(file_path)
            results['metadata']['file_type'] = 'PDF'
        else:
            results['metadata'] = self._analyze_image_metadata(file_path)
            text = self._ocr_image(file_path) if HAS_TESSERACT else ""
            image = Image.open(file_path)
            results['metadata']['file_type'] = 'Image'
        
        # Store image for AI analysis
        self._current_image = image
        self._current_image_path = file_path
        
        # Run all checks
        self._check_metadata_flags(results['metadata'])
        self._check_creation_date(results['metadata'], doc_type)
        self._check_creator_tool(results['metadata'])
        self._check_file_anomalies(file_path, results['metadata'])
        
        if text:
            results['extracted_data'] = self._extract_document_data(text, doc_type)
            self._check_text_anomalies(text, doc_type)
            
            if doc_type == "Pay Stub":
                results['math_validation'] = self._validate_pay_stub_math(text, results['extracted_data'])
            elif doc_type == "W-2":
                results['math_validation'] = self._validate_w2_math(text, results['extracted_data'])
        
        # Visual/forensic analysis
        if image:
            results['visual_analysis'] = self._analyze_visual_forensics(image)
        
        # AI Analysis - the big guns
        if self.use_ai and image:
            results['ai_analysis'] = self._run_ai_vision_analysis(file_path, doc_type, text, results)
        
        # Generate recommendations
        results['recommendations'] = self._generate_recommendations(results)
        
        # Compile results
        results['flags'] = self.flags
        results['risk_score'] = max(0, min(self.risk_score, 100))
        results['risk_level'] = self._calculate_risk_level(results['risk_score'])
        
        return results
    
    def _compute_hash(self, file_path: str) -> str:
        """Compute SHA-256 hash of file for tracking."""
        sha256 = hashlib.sha256()
        with open(file_path, 'rb') as f:
            for chunk in iter(lambda: f.read(4096), b''):
                sha256.update(chunk)
        return sha256.hexdigest()[:16]
    
    def _analyze_pdf_metadata(self, file_path: str) -> Dict:
        """Extract and analyze PDF metadata."""
        metadata = {
            'file_size': f"{os.path.getsize(file_path) / 1024:.1f} KB",
            'file_size_bytes': os.path.getsize(file_path),
        }
        
        if not HAS_PYMUPDF:
            return metadata
        
        try:
            doc = fitz.open(file_path)
            meta = doc.metadata
            
            metadata['pages'] = len(doc)
            metadata['creator'] = meta.get('creator', '')
            metadata['producer'] = meta.get('producer', '')
            metadata['author'] = meta.get('author', '')
            metadata['title'] = meta.get('title', '')
            metadata['subject'] = meta.get('subject', '')
            
            # Parse dates
            if meta.get('creationDate'):
                metadata['creation_date'] = self._parse_pdf_date(meta['creationDate'])
                metadata['creation_date_raw'] = meta['creationDate']
            
            if meta.get('modDate'):
                metadata['modification_date'] = self._parse_pdf_date(meta['modDate'])
                metadata['modification_date_raw'] = meta['modDate']
            
            # Check for incremental saves (sign of editing)
            metadata['has_incremental_saves'] = doc.is_repaired or doc.needs_pass
            
            # Check for embedded files/attachments
            metadata['has_attachments'] = len(doc.embfile_names()) > 0
            
            # Check for JavaScript (suspicious in a pay stub)
            has_js = False
            for page in doc:
                if page.get_text("dict").get("scripts"):
                    has_js = True
                    break
            metadata['has_javascript'] = has_js
            
            # Check for forms
            metadata['has_forms'] = doc.is_form_pdf
            
            # Get PDF version
            metadata['pdf_version'] = f"PDF {doc.metadata.get('format', 'Unknown')}"
            
            doc.close()
        except Exception as e:
            metadata['error'] = str(e)
        
        return metadata
    
    def _analyze_image_metadata(self, file_path: str) -> Dict:
        """Extract image metadata (EXIF, etc.)."""
        metadata = {
            'file_size': f"{os.path.getsize(file_path) / 1024:.1f} KB",
            'file_size_bytes': os.path.getsize(file_path),
        }
        
        try:
            img = Image.open(file_path)
            metadata['format'] = img.format
            metadata['size'] = f"{img.width}x{img.height}"
            metadata['width'] = img.width
            metadata['height'] = img.height
            metadata['mode'] = img.mode
            metadata['dpi'] = img.info.get('dpi', 'Unknown')
            
            # EXIF data
            exif = img._getexif() if hasattr(img, '_getexif') and img._getexif() else {}
            if exif:
                # Common EXIF tags
                tag_names = {
                    271: 'camera_make',
                    272: 'camera_model', 
                    305: 'software',
                    306: 'datetime',
                    36867: 'datetime_original',
                    37521: 'datetime_digitized',
                }
                for tag_id, name in tag_names.items():
                    if tag_id in exif:
                        metadata[name] = str(exif[tag_id])
                
                if 'software' in metadata:
                    metadata['creator'] = metadata['software']
                if 'datetime' in metadata:
                    metadata['creation_date'] = metadata['datetime']
            
            # Check for editing indicators
            metadata['has_exif'] = bool(exif)
            
        except Exception as e:
            metadata['error'] = str(e)
        
        return metadata
    
    def _parse_pdf_date(self, date_str: str) -> str:
        """Parse PDF date format (D:YYYYMMDDHHmmSS)."""
        try:
            if date_str.startswith('D:'):
                date_str = date_str[2:]
            date_str = re.sub(r"[+-]\d{2}'\d{2}'?$", '', date_str)
            date_str = date_str[:14]
            dt = datetime.strptime(date_str, '%Y%m%d%H%M%S')
            return dt.strftime('%Y-%m-%d %H:%M:%S')
        except:
            return date_str
    
    def _extract_pdf_text(self, file_path: str) -> str:
        """Extract text from PDF."""
        if not HAS_PYMUPDF:
            return ""
        
        try:
            doc = fitz.open(file_path)
            text = ""
            for page in doc:
                text += page.get_text()
            doc.close()
            return text
        except:
            return ""
    
    def _pdf_to_image(self, file_path: str, dpi: int = 200) -> Optional[Image.Image]:
        """Convert first page of PDF to image for visual analysis."""
        if not HAS_PYMUPDF:
            return None
        
        try:
            doc = fitz.open(file_path)
            page = doc[0]
            mat = fitz.Matrix(dpi/72, dpi/72)
            pix = page.get_pixmap(matrix=mat)
            img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
            doc.close()
            return img
        except:
            return None
    
    def _ocr_image(self, file_path: str) -> str:
        """Run OCR on image."""
        if not HAS_TESSERACT:
            return ""
        
        try:
            img = Image.open(file_path)
            # Preprocess for better OCR
            if img.mode != 'RGB':
                img = img.convert('RGB')
            text = pytesseract.image_to_string(img)
            return text
        except:
            return ""
    
    def _check_metadata_flags(self, metadata: Dict):
        """Check metadata for suspicious indicators."""
        # Check if metadata is stripped
        creator = metadata.get('creator', '')
        producer = metadata.get('producer', '')
        
        if not creator and not producer:
            self._add_flag(
                'Metadata Missing',
                'Document metadata has been stripped or is missing. This is common with scanned documents but can also indicate tampering.',
                'info',
                10  # Reduced from 20 - too common with legitimate scans
            )
        
        # Check for JavaScript in PDF
        if metadata.get('has_javascript'):
            self._add_flag(
                'JavaScript Detected',
                'PDF contains JavaScript code. Legitimate pay stubs should not contain scripts.',
                'critical',
                35
            )
        
        # Check for unusual file size
        size_bytes = metadata.get('file_size_bytes', 0)
        if size_bytes < 5000:  # Less than 5KB
            self._add_flag(
                'Unusually Small File',
                f'File is only {size_bytes/1024:.1f}KB. This could indicate a digitally created document rather than a scan.',
                'info',
                8  # Reduced from 15 - small files can be legitimate
            )
        elif size_bytes > 10000000:  # More than 10MB
            self._add_flag(
                'Unusually Large File',
                f'File is {size_bytes/1024/1024:.1f}MB. This is unusually large for a single pay stub.',
                'info',
                5
            )
    
    def _check_creation_date(self, metadata: Dict, doc_type: str):
        """Check if creation date is suspicious - smart detection for portal downloads."""
        creation_date = metadata.get('creation_date')
        if not creation_date:
            return
        
        try:
            for fmt in ['%Y-%m-%d %H:%M:%S', '%Y:%m:%d %H:%M:%S', '%Y-%m-%d']:
                try:
                    created = datetime.strptime(creation_date.split()[0], fmt.split()[0])
                    break
                except:
                    continue
            else:
                return
            
            days_old = (datetime.now() - created).days
            hours_old = (datetime.now() - created).total_seconds() / 3600
            
            # Check modification date vs creation date FIRST - this is the real red flag
            mod_date = metadata.get('modification_date')
            was_modified = mod_date and mod_date != creation_date
            
            if was_modified:
                self._add_flag(
                    'Document Modified After Creation',
                    f'Created: {creation_date}, Modified: {mod_date}. The document was edited after initial creation. This is a significant fraud indicator.',
                    'critical',
                    30
                )
            
            # For recent creation dates, context matters:
            # - Pay stubs, bank statements are EXPECTED to be recently created (downloaded from portals)
            # - Modification after creation is the real red flag
            # - Only flag recent creation as suspicious if combined with other factors
            
            portal_download_types = ['Pay Stub', 'Bank Statement', 'W-2', 'Tax Document', '1099']
            is_portal_type = doc_type in portal_download_types
            
            if hours_old < 24:
                if is_portal_type and not was_modified:
                    # Normal for portal downloads - just informational
                    self._add_flag(
                        'Recently Downloaded',
                        f'Document was created within the last {int(hours_old)} hours. This is typical for documents downloaded from payroll or banking portals.',
                        'info',
                        0  # No risk score impact
                    )
                elif was_modified:
                    # Recently created AND modified - very suspicious
                    self._add_flag(
                        'Created and Modified Today',
                        f'Document was created AND modified within the last {int(hours_old)} hours. This suggests active editing.',
                        'critical',
                        25
                    )
                else:
                    # Unknown doc type, recently created - mild flag
                    self._add_flag(
                        'Created Today',
                        f'Document was created within the last {int(hours_old)} hours.',
                        'info',
                        5
                    )
            elif days_old < 7:
                if is_portal_type and not was_modified:
                    # Still normal for portal downloads
                    self._add_flag(
                        'Recently Created',
                        f'Document was created {days_old} days ago. Normal for documents downloaded from employer/bank portals.',
                        'info',
                        0
                    )
                elif not is_portal_type:
                    self._add_flag(
                        'Recently Created',
                        f'Document was created within the last week ({days_old} days ago).',
                        'info',
                        5
                    )
                
        except Exception:
            pass
    
    def _check_creator_tool(self, metadata: Dict):
        """Check if document was created with suspicious software."""
        creator = (metadata.get('creator', '') or '').lower()
        producer = (metadata.get('producer', '') or '').lower()
        software = (metadata.get('software', '') or '').lower()
        
        combined = f"{creator} {producer} {software}"
        
        # Check for AI indicators first (highest risk)
        for indicator, score in self.AI_INDICATORS:
            if indicator in combined:
                self._add_flag(
                    'AI Generation Detected',
                    f'Document metadata suggests AI-generated content: "{indicator}" found in creator info.',
                    'critical',
                    score
                )
                return
        
        # Check for suspicious editing tools
        for tool_key, (tool_name, score) in self.SUSPICIOUS_CREATORS.items():
            if tool_key in combined:
                severity = 'critical' if score >= 30 else 'warning'
                self._add_flag(
                    f'Suspicious Software: {tool_name}',
                    f'Document was created/edited with {tool_name}. Legitimate payroll documents come directly from payroll systems.',
                    severity,
                    score
                )
                return
        
        # Check for legitimate payroll software (reduces risk)
        for legit_key, legit_name in self.LEGITIMATE_CREATORS.items():
            if legit_key in combined:
                self._add_flag(
                    f'Legitimate Source: {legit_name}',
                    f'Document appears to originate from {legit_name} payroll system.',
                    'info',
                    -25  # Increased bonus from -15 - legitimate sources should offset other flags
                )
                return
    
    def _check_file_anomalies(self, file_path: str, metadata: Dict):
        """Check for file-level anomalies."""
        ext = Path(file_path).suffix.lower()
        
        # Check file extension vs actual content
        if ext == '.pdf':
            with open(file_path, 'rb') as f:
                header = f.read(10)
                if not header.startswith(b'%PDF'):
                    self._add_flag(
                        'File Type Mismatch',
                        'File has .pdf extension but does not appear to be a valid PDF.',
                        'critical',
                        40
                    )
    
    def _check_text_anomalies(self, text: str, doc_type: str):
        """Check extracted text for anomalies."""
        text_lower = text.lower()
        
        # Check for placeholder text that wasn't replaced
        placeholders = ['lorem ipsum', 'xxx-xx-xxxx', 'john doe', 'jane doe', 
                       '[company name]', '[employee name]', 'sample', 'example',
                       'test document', 'draft']
        for placeholder in placeholders:
            if placeholder in text_lower:
                self._add_flag(
                    'Placeholder Text Found',
                    f'Document contains placeholder text: "{placeholder}". This suggests a template that wasn\'t fully customized.',
                    'critical',
                    30
                )
                break
        
        # Check for invalid text in fields that should be numeric or blank
        invalid_field_values = ['n/a', 'not needed', 'not applicable', 'none', 'na', 'n.a.', 
                                'see attached', 'refer to', 'tbd', 'pending']
        for invalid_val in invalid_field_values:
            # Look for these near dollar signs, box numbers, or common W2/pay stub fields
            patterns = [
                rf'\$\s*{re.escape(invalid_val)}',
                rf'box\s*\d+[:\s]*{re.escape(invalid_val)}',
                rf'wages[:\s]*{re.escape(invalid_val)}',
                rf'tax[:\s]*{re.escape(invalid_val)}',
                rf'gross[:\s]*{re.escape(invalid_val)}',
                rf'net[:\s]*{re.escape(invalid_val)}',
                rf'withholding[:\s]*{re.escape(invalid_val)}',
            ]
            for pattern in patterns:
                if re.search(pattern, text_lower):
                    self._add_flag(
                        'Invalid Field Value',
                        f'Document contains "{invalid_val}" in a field that should be numeric or blank. Legitimate payroll systems use 0 or leave fields empty.',
                        'critical',
                        35
                    )
                    break
        
        # Check for missing or suspicious year formats on W-2s
        if doc_type == "W-2":
            # Look for tax year - should be prominently displayed
            year_pattern = r'(?:tax\s*year|form\s*w-?2)[:\s]*(\d{4}|\d{2})'
            year_match = re.search(year_pattern, text_lower)
            
            # Check if year is missing entirely
            current_year = datetime.now().year
            valid_years = [str(y) for y in range(current_year - 5, current_year + 1)]
            has_valid_year = any(year in text for year in valid_years)
            
            if not has_valid_year:
                self._add_flag(
                    'Missing Tax Year',
                    'W-2 does not contain a clearly visible tax year. This is required on all legitimate W-2 forms.',
                    'critical',
                    40
                )
        
        # Check for inconsistent date formats
        date_patterns = [
            r'\d{1,2}/\d{1,2}/\d{2,4}',  # MM/DD/YYYY
            r'\d{1,2}-\d{1,2}-\d{2,4}',  # MM-DD-YYYY
            r'\d{4}-\d{2}-\d{2}',         # YYYY-MM-DD
        ]
        found_formats = set()
        for pattern in date_patterns:
            if re.search(pattern, text):
                found_formats.add(pattern)
        
        if len(found_formats) > 1:
            self._add_flag(
                'Inconsistent Date Formats',
                'Document uses multiple date formats, which is unusual for system-generated documents.',
                'warning',
                15
            )
        
        # Check for suspicious phrases
        suspicious_phrases = [
            'proof of income', 'verification purposes', 'this is to certify',
            'generated for', 'created for verification'
        ]
        for phrase in suspicious_phrases:
            if phrase in text_lower:
                self._add_flag(
                    'Unusual Language',
                    f'Document contains phrase "{phrase}" which is uncommon in legitimate payroll documents.',
                    'warning',
                    10
                )
                break
    
    def _extract_document_data(self, text: str, doc_type: str) -> Dict:
        """Extract structured data from document text."""
        data = {}
        
        # Common patterns
        ssn_match = re.search(r'(?:SSN|Social)[:\s]*(?:XXX-XX-|xxx-xx-|\*\*\*-\*\*-)(\d{4})', text, re.I)
        if ssn_match:
            data['ssn_last4'] = ssn_match.group(1)
        
        ein_match = re.search(r'(?:EIN|Employer ID)[:\s]*(\d{2}-\d{7})', text, re.I)
        if ein_match:
            data['ein'] = ein_match.group(1)
        
        # Extract all money amounts
        amounts = re.findall(r'\$[\d,]+\.?\d*', text)
        if amounts:
            # Parse and sort amounts
            parsed = []
            for amt in amounts:
                try:
                    val = float(amt.replace('$', '').replace(',', ''))
                    parsed.append(val)
                except:
                    pass
            if parsed:
                data['amounts_found'] = len(parsed)
                data['largest_amount'] = max(parsed)
                data['smallest_amount'] = min(parsed)
        
        # Pay stub specific extraction
        if doc_type == "Pay Stub":
            patterns = {
                'gross_pay': [
                    r'(?:gross\s*pay|gross\s*earnings?|total\s*earnings?)[:\s]*\$?([\d,]+\.?\d*)',
                    r'(?:current\s*gross)[:\s]*\$?([\d,]+\.?\d*)',
                ],
                'net_pay': [
                    r'(?:net\s*pay|take\s*home|net\s*amount)[:\s]*\$?([\d,]+\.?\d*)',
                    r'(?:current\s*net)[:\s]*\$?([\d,]+\.?\d*)',
                ],
                'federal_tax': [
                    r'(?:federal\s*tax|fed\s*tax|federal\s*withholding)[:\s]*\$?([\d,]+\.?\d*)',
                    r'(?:fed\s*w/?h)[:\s]*\$?([\d,]+\.?\d*)',
                ],
                'state_tax': [
                    r'(?:state\s*tax|state\s*withholding)[:\s]*\$?([\d,]+\.?\d*)',
                ],
                'pay_period': [
                    r'(?:pay\s*period|period)[:\s]*(\d{1,2}/\d{1,2}/\d{2,4})\s*(?:to|-)\s*(\d{1,2}/\d{1,2}/\d{2,4})',
                ],
                'pay_date': [
                    r'(?:pay\s*date|check\s*date)[:\s]*(\d{1,2}/\d{1,2}/\d{2,4})',
                ],
                'hourly_rate': [
                    r'(?:hourly\s*rate|rate)[:\s]*\$?([\d,]+\.?\d*)',
                ],
                'hours_worked': [
                    r'(?:hours|regular\s*hours)[:\s]*([\d.]+)',
                ],
            }
            
            for field, field_patterns in patterns.items():
                for pattern in field_patterns:
                    match = re.search(pattern, text, re.I)
                    if match:
                        if field == 'pay_period':
                            data['pay_period_start'] = match.group(1)
                            data['pay_period_end'] = match.group(2)
                        else:
                            val = match.group(1).replace(',', '')
                            try:
                                data[field] = float(val) if '.' in val else int(val)
                            except:
                                data[field] = val
                        break
        
        # W-2 specific extraction
        elif doc_type == "W-2":
            w2_patterns = {
                'wages': r'(?:box\s*1|wages,?\s*tips)[:\s]*\$?([\d,]+\.?\d*)',
                'federal_withheld': r'(?:box\s*2|federal.*withheld)[:\s]*\$?([\d,]+\.?\d*)',
                'social_security_wages': r'(?:box\s*3|social\s*security\s*wages)[:\s]*\$?([\d,]+\.?\d*)',
                'social_security_tax': r'(?:box\s*4|social\s*security\s*tax)[:\s]*\$?([\d,]+\.?\d*)',
                'medicare_wages': r'(?:box\s*5|medicare\s*wages)[:\s]*\$?([\d,]+\.?\d*)',
                'medicare_tax': r'(?:box\s*6|medicare\s*tax)[:\s]*\$?([\d,]+\.?\d*)',
                'state_wages': r'(?:box\s*16|state\s*wages)[:\s]*\$?([\d,]+\.?\d*)',
                'state_tax': r'(?:box\s*17|state.*tax)[:\s]*\$?([\d,]+\.?\d*)',
            }
            
            for field, pattern in w2_patterns.items():
                match = re.search(pattern, text, re.I)
                if match:
                    val = match.group(1).replace(',', '')
                    try:
                        data[field] = float(val)
                    except:
                        data[field] = val
        
        return data
    
    def _validate_pay_stub_math(self, text: str, data: Dict) -> Dict:
        """Comprehensive pay stub math validation."""
        result = {'valid': True, 'checks': [], 'errors': []}
        
        gross = data.get('gross_pay')
        net = data.get('net_pay')
        federal_tax = data.get('federal_tax')
        state_tax = data.get('state_tax')
        hourly_rate = data.get('hourly_rate')
        hours = data.get('hours_worked')
        
        # Check 1: Net cannot exceed gross
        if gross and net:
            if net > gross:
                result['valid'] = False
                result['errors'].append({
                    'check': 'Net vs Gross',
                    'error': f'Net pay (${net:,.2f}) exceeds gross pay (${gross:,.2f})',
                    'severity': 'critical'
                })
                self._add_flag(
                    'Math Error: Net > Gross',
                    f'Net pay (${net:,.2f}) cannot exceed gross pay (${gross:,.2f}). This is impossible and indicates fraud.',
                    'critical',
                    45
                )
            else:
                deductions = gross - net
                deduction_pct = (deductions / gross) * 100
                result['checks'].append(f'Deduction rate: {deduction_pct:.1f}%')
                
                # Check reasonable deduction range
                if deduction_pct < 10 and gross > 1000:
                    self._add_flag(
                        'Suspiciously Low Deductions',
                        f'Only {deduction_pct:.1f}% deducted from gross pay. Federal + state taxes alone typically exceed 15%.',
                        'warning',
                        20
                    )
                elif deduction_pct > 60:
                    self._add_flag(
                        'Unusually High Deductions',
                        f'{deduction_pct:.1f}% deducted. This exceeds typical maximum combined tax rates.',
                        'warning',
                        15
                    )
        
        # Check 2: Hours × Rate = Gross (approximately)
        if hourly_rate and hours and gross:
            expected_gross = hourly_rate * hours
            if abs(expected_gross - gross) > gross * 0.1:  # More than 10% off
                result['errors'].append({
                    'check': 'Hours × Rate',
                    'error': f'Hours ({hours}) × Rate (${hourly_rate}) = ${expected_gross:,.2f}, but gross is ${gross:,.2f}',
                    'severity': 'warning'
                })
                self._add_flag(
                    'Hours/Rate Mismatch',
                    f'Calculated gross (${expected_gross:,.2f}) doesn\'t match stated gross (${gross:,.2f}).',
                    'warning',
                    15
                )
        
        # Check 3: Tax withholding reasonableness
        if gross and federal_tax:
            annual_gross = gross * 26  # Assume bi-weekly
            fed_rate = federal_tax / gross
            
            # Find expected bracket
            expected_min, expected_max = 0.05, 0.40
            for bracket_max, min_rate, max_rate in self.TAX_BRACKETS:
                if annual_gross <= bracket_max:
                    expected_min, expected_max = min_rate - 0.05, max_rate + 0.05
                    break
            
            if fed_rate < expected_min or fed_rate > expected_max:
                self._add_flag(
                    'Federal Tax Rate Anomaly',
                    f'Federal withholding rate ({fed_rate*100:.1f}%) is outside expected range ({expected_min*100:.0f}%-{expected_max*100:.0f}%) for this income level.',
                    'warning',
                    15
                )
        
        return result
    
    def _validate_w2_math(self, text: str, data: Dict) -> Dict:
        """Comprehensive W-2 validation."""
        result = {'valid': True, 'checks': [], 'errors': []}
        
        wages = data.get('wages')
        federal = data.get('federal_withheld')
        ss_wages = data.get('social_security_wages')
        ss_tax = data.get('social_security_tax')
        medicare_wages = data.get('medicare_wages')
        medicare_tax = data.get('medicare_tax')
        
        # Check 1: Federal withholding rate
        if wages and federal:
            fed_rate = federal / wages
            if fed_rate > 0.50:
                result['valid'] = False
                result['errors'].append({
                    'check': 'Federal Rate',
                    'error': f'Federal withholding ({fed_rate*100:.1f}%) exceeds maximum possible rate'
                })
                self._add_flag(
                    'Impossible Federal Tax Rate',
                    f'Federal withholding is {fed_rate*100:.1f}% of wages. Maximum federal rate is 37%.',
                    'critical',
                    40
                )
            else:
                result['checks'].append(f'Federal rate: {fed_rate*100:.1f}%')
        
        # Check 2: Social Security tax calculation (6.2% of wages up to cap)
        SS_RATE = 0.062
        SS_CAP_2024 = 168600
        
        if ss_wages and ss_tax:
            expected_ss = min(ss_wages, SS_CAP_2024) * SS_RATE
            if abs(ss_tax - expected_ss) > 100:  # Allow $100 tolerance
                result['errors'].append({
                    'check': 'SS Tax',
                    'error': f'SS tax should be ~${expected_ss:,.2f} but is ${ss_tax:,.2f}'
                })
                self._add_flag(
                    'Social Security Tax Mismatch',
                    f'SS tax (${ss_tax:,.2f}) doesn\'t match expected (${expected_ss:,.2f} = 6.2% of wages).',
                    'warning',
                    20
                )
            else:
                result['checks'].append(f'SS tax verified: ${ss_tax:,.2f}')
        
        # Check 3: Medicare tax calculation (1.45% of all wages)
        MEDICARE_RATE = 0.0145
        
        if medicare_wages and medicare_tax:
            expected_med = medicare_wages * MEDICARE_RATE
            if abs(medicare_tax - expected_med) > 50:
                result['errors'].append({
                    'check': 'Medicare Tax', 
                    'error': f'Medicare tax should be ~${expected_med:,.2f} but is ${medicare_tax:,.2f}'
                })
                self._add_flag(
                    'Medicare Tax Mismatch',
                    f'Medicare tax (${medicare_tax:,.2f}) doesn\'t match expected (${expected_med:,.2f} = 1.45% of wages).',
                    'warning',
                    20
                )
            else:
                result['checks'].append(f'Medicare tax verified: ${medicare_tax:,.2f}')
        
        # Check 4: Wages consistency
        if wages and ss_wages and medicare_wages:
            if wages != ss_wages or wages != medicare_wages:
                # This can be legitimate (wages above SS cap), but flag it
                if wages > SS_CAP_2024 and ss_wages == SS_CAP_2024:
                    result['checks'].append('Wages above SS cap - expected difference')
                elif abs(wages - ss_wages) > 1000 or abs(wages - medicare_wages) > 1000:
                    self._add_flag(
                        'Wage Amounts Inconsistent',
                        f'Box 1 (${wages:,.2f}), Box 3 (${ss_wages:,.2f}), Box 5 (${medicare_wages:,.2f}) show significant differences.',
                        'warning',
                        10
                    )
        
        return result
    
    def _analyze_visual_forensics(self, image: Image.Image) -> Dict:
        """Perform visual forensic analysis on the document image."""
        results = {
            'checks_performed': [],
            'anomalies': []
        }
        
        if image is None:
            return results
        
        try:
            # Convert to RGB if needed
            if image.mode != 'RGB':
                image = image.convert('RGB')
            
            img_array = np.array(image)
            
            # Check 1: Aspect ratio
            width, height = image.size
            aspect = width / height
            results['aspect_ratio'] = round(aspect, 3)
            results['checks_performed'].append('Aspect ratio check')
            
            if aspect < 0.6 or aspect > 0.9:
                if not (0.7 < aspect < 0.8):  # Not close to letter/A4
                    self._add_flag(
                        'Unusual Document Dimensions',
                        f'Aspect ratio ({aspect:.2f}) differs from standard letter (0.77) or A4 (0.71) paper.',
                        'info',
                        5
                    )
            
            # Check 2: Resolution/DPI estimation
            results['resolution'] = f"{width}x{height}"
            if width < 800 or height < 1000:
                self._add_flag(
                    'Low Resolution',
                    f'Document resolution ({width}x{height}) is below typical scan quality. May indicate screenshot or low-quality source.',
                    'warning',
                    10
                )
            
            # Check 3: Color analysis - pay stubs are usually mostly white/light
            results['checks_performed'].append('Color distribution analysis')
            
            # Calculate mean brightness
            gray = image.convert('L')
            stat = ImageStat.Stat(gray)
            mean_brightness = stat.mean[0]
            results['mean_brightness'] = round(mean_brightness, 1)
            
            if mean_brightness < 180:  # Document should be mostly white
                self._add_flag(
                    'Unusual Color Profile',
                    f'Document is darker than typical (brightness: {mean_brightness:.0f}/255). Legitimate pay stubs are usually on white paper.',
                    'info',
                    5
                )
            
            # Check 4: Edge detection for potential copy-paste artifacts
            results['checks_performed'].append('Edge artifact analysis')
            edges = image.filter(ImageFilter.FIND_EDGES)
            edge_stat = ImageStat.Stat(edges.convert('L'))
            edge_intensity = edge_stat.mean[0]
            results['edge_intensity'] = round(edge_intensity, 2)
            
            # Very high edge intensity might indicate manipulation
            if edge_intensity > 30:
                results['anomalies'].append('High edge intensity detected')
            
            # Check 5: Noise analysis
            results['checks_performed'].append('Noise pattern analysis')
            
            # Look for uniform noise (natural) vs irregular noise (edited)
            small = image.resize((100, 140))
            small_array = np.array(small.convert('L'), dtype=float)
            
            # Calculate local variance
            from scipy import ndimage
            local_var = ndimage.generic_filter(small_array, np.var, size=5)
            var_of_var = np.var(local_var)
            results['noise_uniformity'] = round(var_of_var, 2)
            
        except ImportError:
            # scipy not available, skip advanced analysis
            pass
        except Exception as e:
            results['error'] = str(e)
        
        return results
    
    def _run_ai_vision_analysis(self, file_path: str, doc_type: str, text: str, 
                                 current_results: Dict) -> Dict:
        """Run comprehensive AI vision analysis using Claude."""
        if not self.use_ai:
            return {'available': False, 'reason': 'AI analysis not configured'}
        
        try:
            # Prepare image for API
            ext = Path(file_path).suffix.lower()
            
            if ext == '.pdf':
                # Use the converted image
                if self._current_image:
                    img_buffer = io.BytesIO()
                    self._current_image.save(img_buffer, format='PNG')
                    img_data = base64.standard_b64encode(img_buffer.getvalue()).decode('utf-8')
                    media_type = 'image/png'
                else:
                    return {'available': False, 'reason': 'Could not convert PDF to image'}
            else:
                with open(file_path, 'rb') as f:
                    img_data = base64.standard_b64encode(f.read()).decode('utf-8')
                media_type = f'image/{ext[1:]}'
                if ext == '.jpg':
                    media_type = 'image/jpeg'
            
            # Build context from current findings
            context = f"""
Document Type: {doc_type}
Creator Software: {current_results.get('metadata', {}).get('creator', 'Unknown')}
Creation Date: {current_results.get('metadata', {}).get('creation_date', 'Unknown')}
Current Risk Score: {self.risk_score}
Flags Found So Far: {len(self.flags)}
"""
            
            # Comprehensive prompt for fraud detection
            prompt = f"""You are an expert forensic document analyst specializing in employment verification fraud detection. Analyze this {doc_type} image for signs of fraud or manipulation.

CONTEXT:
{context}

ANALYZE FOR:

1. **Font Consistency** (CRITICAL - Common fraud indicator)
   - Are ALL fonts consistent throughout the document? Check EVERY text element.
   - Look for font mismatches in: dates, years, dollar amounts, names, addresses
   - Check if any text appears darker, bolder, or in a different typeface than surrounding text
   - Look for text that appears to have been added later (different font weight, size, or style)
   - Check if numbers in the same column use different fonts

2. **Year/Date Tampering** (CRITICAL - Very common on fake W-2s)
   - Is the tax year clearly visible and in the same font as other text?
   - Look for years that appear printed ON TOP of other text (overprint)
   - Check for black boxes, white boxes, or rectangles covering original dates with new dates overlaid
   - Look for dates where the font color or darkness differs from surrounding text
   - Check if year digits appear misaligned or at different baselines
   - Look for any rectangular areas that seem to cover/redact original content

3. **Invalid Field Values**
   - Check for "N/A", "Not Needed", "None", or similar text in boxes that should contain numbers or be blank
   - Legitimate W-2s and pay stubs use $0.00 or leave fields empty - never "N/A"

4. **Visual Consistency**
   - Is text alignment uniform throughout?
   - Do numbers align properly in columns?
   - Are there any visible cut/paste lines, edges, or artifacts?
   - Look for areas with different compression, blur, or sharpness levels

5. **Template Authenticity** 
   - Does this look like a genuine payroll system output (ADP, Paychex, etc.)?
   - Is the layout consistent with professional payroll software?
   - Are logos/headers crisp or potentially copied/pasted?

6. **Manipulation Indicators**
   - Any signs of image editing (blur around certain text, sharpening differences)?
   - Inconsistent shadows or lighting around text elements?
   - Text that appears to float or not sit naturally on the background?
   - Different quality/resolution in different areas of the document?
   - White or colored rectangles that might be covering original content?

RESPOND IN THIS JSON FORMAT:
{{
    "overall_assessment": "LIKELY_LEGITIMATE" | "SUSPICIOUS" | "LIKELY_FRAUDULENT",
    "confidence": 0-100,
    "font_consistency": {{
        "consistent": true/false,
        "issues": ["describe each font mismatch found - location and nature of mismatch"]
    }},
    "date_year_tampering": {{
        "detected": true/false,
        "issues": ["describe any year/date tampering: overprints, covered text, font differences in dates"]
    }},
    "invalid_field_values": {{
        "detected": true/false,
        "issues": ["list any N/A, Not Needed, or similar invalid text in numeric fields"]
    }},
    "visual_consistency": {{
        "score": 0-100,
        "issues": ["list of visual issues found"]
    }},
    "template_authenticity": {{
        "score": 0-100,
        "appears_to_be": "description of apparent source",
        "concerns": ["list of concerns"]
    }},
    "manipulation_indicators": {{
        "detected": true/false,
        "indicators": ["list of specific indicators: blur, cut lines, rectangles covering text, etc."]
    }},
    "key_findings": ["most important findings, max 5"],
    "recommendation": "brief recommendation for the reviewer"
}}"""

            response = self.ai_client.messages.create(
                model="claude-sonnet-4-20250514",
                max_tokens=1500,
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "image",
                                "source": {
                                    "type": "base64",
                                    "media_type": media_type,
                                    "data": img_data,
                                },
                            },
                            {
                                "type": "text",
                                "text": prompt
                            }
                        ],
                    }
                ],
            )
            
            # Parse the response
            response_text = response.content[0].text
            
            # Try to extract JSON from response
            json_match = re.search(r'\{[\s\S]*\}', response_text)
            if json_match:
                try:
                    ai_result = json.loads(json_match.group())
                    
                    # Add flags based on AI findings
                    assessment = ai_result.get('overall_assessment', '')
                    confidence = ai_result.get('confidence', 50)
                    
                    if assessment == 'LIKELY_FRAUDULENT':
                        self._add_flag(
                            'AI Analysis: Likely Fraudulent',
                            f"AI detected significant fraud indicators with {confidence}% confidence. Key findings: {', '.join(ai_result.get('key_findings', [])[:3])}",
                            'critical',
                            35
                        )
                    elif assessment == 'SUSPICIOUS':
                        self._add_flag(
                            'AI Analysis: Suspicious Elements',
                            f"AI identified suspicious elements ({confidence}% confidence). Review recommended: {ai_result.get('recommendation', 'Manual review advised')}",
                            'warning',
                            20
                        )
                    else:
                        self._add_flag(
                            'AI Analysis: Appears Legitimate',
                            f"AI analysis found no significant fraud indicators ({confidence}% confidence).",
                            'info',
                            -10
                        )
                    
                    # Add font consistency flags
                    font_check = ai_result.get('font_consistency', {})
                    if font_check.get('consistent') == False:
                        font_issues = font_check.get('issues', [])
                        for issue in font_issues[:3]:
                            self._add_flag(
                                'Font Mismatch Detected',
                                issue,
                                'critical',
                                25
                            )
                    
                    # Add date/year tampering flags
                    date_check = ai_result.get('date_year_tampering', {})
                    if date_check.get('detected'):
                        date_issues = date_check.get('issues', [])
                        for issue in date_issues[:2]:
                            self._add_flag(
                                'Date/Year Tampering Detected',
                                issue,
                                'critical',
                                35
                            )
                    
                    # Add invalid field value flags from AI
                    invalid_check = ai_result.get('invalid_field_values', {})
                    if invalid_check.get('detected'):
                        invalid_issues = invalid_check.get('issues', [])
                        for issue in invalid_issues[:2]:
                            self._add_flag(
                                'Invalid Field Value (AI)',
                                issue,
                                'critical',
                                30
                            )
                    
                    # Add manipulation indicator flags
                    if ai_result.get('manipulation_indicators', {}).get('detected'):
                        indicators = ai_result['manipulation_indicators'].get('indicators', [])
                        for indicator in indicators[:2]:
                            self._add_flag(
                                'AI Detected Manipulation',
                                indicator,
                                'critical',
                                15
                            )
                    
                    return {
                        'available': True,
                        'result': ai_result,
                        'raw_response': response_text
                    }
                    
                except json.JSONDecodeError:
                    pass
            
            # If JSON parsing failed, return raw response
            return {
                'available': True,
                'result': {'raw_analysis': response_text},
                'parsing_note': 'Could not parse structured response'
            }
            
        except Exception as e:
            return {
                'available': False,
                'error': str(e)
            }
    
    def _generate_recommendations(self, results: Dict) -> List[str]:
        """Generate actionable recommendations based on analysis."""
        recommendations = []
        
        risk_score = self.risk_score
        flags = self.flags
        
        critical_flags = [f for f in flags if f.get('severity') == 'critical']
        warning_flags = [f for f in flags if f.get('severity') == 'warning']
        
        if risk_score >= 65 or len(critical_flags) >= 2:
            recommendations.append("⛔ HIGH RISK: Request alternative documentation or direct employer verification")
            recommendations.append("📞 Contact the employer directly using independently verified contact information")
            recommendations.append("🔍 Request original documents if only copies were provided")
        elif risk_score >= 35 or len(critical_flags) >= 1:
            recommendations.append("⚠️ ELEVATED RISK: Additional verification recommended")
            recommendations.append("📋 Cross-reference with other provided documents")
            recommendations.append("📞 Consider direct employer verification for this candidate")
        else:
            recommendations.append("✅ Document appears legitimate based on automated analysis")
            recommendations.append("👁️ Perform standard visual review as part of normal process")
        
        # Specific recommendations based on flags
        for flag in critical_flags:
            if 'AI' in flag['title'] or 'Photoshop' in flag['title']:
                recommendations.append("🤖 AI/editing software detected - request original payroll system export")
            if 'Math' in flag['title']:
                recommendations.append("🧮 Mathematical errors found - likely fabricated document")
            if 'Created Today' in flag['title']:
                recommendations.append("📅 Document created very recently - verify pay period dates match")
        
        return recommendations[:5]  # Max 5 recommendations
    
    def _add_flag(self, title: str, description: str, severity: str, score_impact: int):
        """Add a fraud indicator flag."""
        self.flags.append({
            'title': title,
            'description': description,
            'severity': severity,
            'score_impact': score_impact
        })
        self.risk_score += score_impact
    
    def _calculate_risk_level(self, score: int) -> str:
        """Calculate overall risk level from score.
        
        Thresholds adjusted 2026-05-21 to reduce false positives:
        - HIGH: 65+ (was 50) - Strong fraud indicators
        - MEDIUM: 35-64 (was 25-49) - Needs review
        - LOW: 0-34 (was 0-24) - Appears legitimate
        """
        if score >= 65:
            return 'HIGH'
        elif score >= 35:
            return 'MEDIUM'
        else:
            return 'LOW'


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        analyzer = DocumentAnalyzer(use_ai=True)
        results = analyzer.analyze(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else "Pay Stub")
        
        print(f"\n{'='*60}")
        print(f"DOCUMENT FRAUD ANALYSIS REPORT")
        print(f"{'='*60}")
        print(f"\nRisk Level: {results['risk_level']}")
        print(f"Risk Score: {results['risk_score']}/100")
        print(f"\nFlags ({len(results['flags'])}):")
        for flag in results['flags']:
            icon = '🔴' if flag['severity'] == 'critical' else '🟡' if flag['severity'] == 'warning' else '🔵'
            print(f"  {icon} {flag['title']}")
            print(f"     {flag['description']}")
        
        print(f"\nRecommendations:")
        for rec in results['recommendations']:
            print(f"  • {rec}")
        
        if results.get('ai_analysis', {}).get('available'):
            print(f"\nAI Analysis Available: Yes")
            ai = results['ai_analysis'].get('result', {})
            if 'overall_assessment' in ai:
                print(f"  Assessment: {ai['overall_assessment']}")
                print(f"  Confidence: {ai.get('confidence', 'N/A')}%")
    else:
        print("Usage: python document_analyzer.py <file_path> [doc_type]")
